Metrics/LineLength:
  Max: 240

Style/EmptyLines:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/MethodLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false
