Metrics/LineLength:
  Max: 120

Style/EmptyLines:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
