AllCops:
  # Include:
  #   - '**/Rakefile'
  #   - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'spec/factories/**/*'


Metrics/LineLength:
  Max: 240

Style/EmptyLines:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/MethodLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/AbcSize:
  Max: 87

Style/EmptyLineBetweenDefs:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/WordArray:
  MinSize: 3

Style/StringLiterals:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6

Metrics/CyclomaticComplexity:
  Max: 14
