language: ruby

rvm: 2.2.2

before_install:
  - gem install bundler

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - "RAILS_ENV=test bundle exec rake db:migrate"

script:
  - bundle exec rspec spec --tag ~@vcr

addons:
  postgresql: "9.3"
