Time::DATE_FORMATS[:draft_date] = "%B %d, %Y"
Time::DATE_FORMATS[:check] = "%Y-%m-%d %H:%M:%S"
Time::DATE_FORMATS[:datetimepicker] = "%Y-%m-%d %H:%M"
Time::DATE_FORMATS[:long_ampm] = "%B %d, %Y %-l:%M %p"
Time::DATE_FORMATS[:short_ampm] = "%d %b %-l:%M%P"
Time::DATE_FORMATS[:ical] = "%Y%m%dT%H%M00Z"
Time::DATE_FORMATS[:filename] = "%Y%m%dT%H%M%SZ"
