# require 'spec_helper'

# # This spec was generated by rspec-rails when you ran the scaffold generator.
# # It demonstrates how one might use RSpec to specify the controller code that
# # was generated by Rails when you ran the scaffold generator.
# #
# # It assumes that the implementation code is generated by the rails scaffold
# # generator.  If you are using any extension libraries to generate different
# # controller code, this generated spec may or may not pass.
# #
# # It only uses APIs available in rails and/or rspec-rails.  There are a number
# # of tools you can use to make these specs even more expressive, but we're
# # sticking to rails and rspec-rails APIs to keep things simple and stable.
# #
# # Compared to earlier versions of this generator, there is very limited use of
# # stubs and message expectations in this spec.  Stubs are only used when there
# # is no simpler way to get a handle on the object needed for the example.
# # Message expectations are only used when there is no simpler way to specify
# # that an instance is receiving a specific message.

# describe SubUnitsController do

#   # This should return the minimal set of attributes required to create a valid
#   # SubUnit. As you add validations to SubUnit, be sure to
#   # update the return value of this method accordingly.
#   def valid_attributes
#     FactoryGirl.attributes_for(:sub_unit)
#   end

#   # This should return the minimal set of values that should be in the session
#   # in order to pass any filters (e.g. authentication) defined in
#   # SubUnitsController. Be sure to keep this updated too.
#   def valid_session
#     {}
#   end

#   describe "GET index" do
#     it "assigns all sub_units as @sub_units" do
#       sub_unit = SubUnit.create! valid_attributes
#       get :index, {}, valid_session
#       assigns(:sub_units).should eq([sub_unit])
#     end
#   end

#   describe "GET show" do
#     it "assigns the requested sub_unit as @sub_unit" do
#       sub_unit = SubUnit.create! valid_attributes
#       get :show, {:id => sub_unit.to_param}, valid_session
#       assigns(:sub_unit).should eq(sub_unit)
#     end
#   end

#   describe "GET new" do
#     it "assigns a new sub_unit as @sub_unit" do
#       get :new, {}, valid_session
#       assigns(:sub_unit).should be_a_new(SubUnit)
#     end
#   end

#   describe "GET edit" do
#     it "assigns the requested sub_unit as @sub_unit" do
#       sub_unit = SubUnit.create! valid_attributes
#       get :edit, {:id => sub_unit.to_param}, valid_session
#       assigns(:sub_unit).should eq(sub_unit)
#     end
#   end

#   describe "POST create" do
#     describe "with valid params" do
#       it "creates a new SubUnit" do
#         expect {
#           post :create, {:sub_unit => valid_attributes}, valid_session
#         }.to change(SubUnit, :count).by(1)
#       end

#       it "assigns a newly created sub_unit as @sub_unit" do
#         post :create, {:sub_unit => valid_attributes}, valid_session
#         assigns(:sub_unit).should be_a(SubUnit)
#         assigns(:sub_unit).should be_persisted
#       end

#       it "redirects to the created sub_unit" do
#         post :create, {:sub_unit => valid_attributes}, valid_session
#         response.should redirect_to(SubUnit.last)
#       end
#     end

#     describe "with invalid params" do
#       it "assigns a newly created but unsaved sub_unit as @sub_unit" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         SubUnit.any_instance.stub(:save).and_return(false)
#         post :create, {:sub_unit => {}}, valid_session
#         assigns(:sub_unit).should be_a_new(SubUnit)
#       end

#       it "re-renders the 'new' template" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         SubUnit.any_instance.stub(:save).and_return(false)
#         post :create, {:sub_unit => {}}, valid_session
#         response.should render_template("new")
#       end
#     end
#   end

#   describe "PUT update" do
#     describe "with valid params" do
#       it "updates the requested sub_unit" do
#         sub_unit = SubUnit.create! valid_attributes
#         # Assuming there are no other sub_units in the database, this
#         # specifies that the SubUnit created on the previous line
#         # receives the :update_attributes message with whatever params are
#         # submitted in the request.
#         SubUnit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
#         put :update, {:id => sub_unit.to_param, :sub_unit => {'these' => 'params'}}, valid_session
#       end

#       it "assigns the requested sub_unit as @sub_unit" do
#         sub_unit = SubUnit.create! valid_attributes
#         put :update, {:id => sub_unit.to_param, :sub_unit => valid_attributes}, valid_session
#         assigns(:sub_unit).should eq(sub_unit)
#       end

#       it "redirects to the sub_unit" do
#         sub_unit = SubUnit.create! valid_attributes
#         put :update, {:id => sub_unit.to_param, :sub_unit => valid_attributes}, valid_session
#         response.should redirect_to(sub_unit)
#       end
#     end

#     describe "with invalid params" do
#       it "assigns the sub_unit as @sub_unit" do
#         sub_unit = SubUnit.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         SubUnit.any_instance.stub(:save).and_return(false)
#         put :update, {:id => sub_unit.to_param, :sub_unit => {}}, valid_session
#         assigns(:sub_unit).should eq(sub_unit)
#       end

#       it "re-renders the 'edit' template" do
#         sub_unit = SubUnit.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         SubUnit.any_instance.stub(:save).and_return(false)
#         put :update, {:id => sub_unit.to_param, :sub_unit => {}}, valid_session
#         response.should render_template("edit")
#       end
#     end
#   end

#   describe "DELETE destroy" do
#     it "destroys the requested sub_unit" do
#       sub_unit = SubUnit.create! valid_attributes
#       expect {
#         delete :destroy, {:id => sub_unit.to_param}, valid_session
#       }.to change(SubUnit, :count).by(-1)
#     end

#     it "redirects to the sub_units list" do
#       sub_unit = SubUnit.create! valid_attributes
#       delete :destroy, {:id => sub_unit.to_param}, valid_session
#       response.should redirect_to(sub_units_url)
#     end
#   end

# end
